const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("usage", {
  onSnapshot: (cb) => ipcRenderer.on("usage://snapshot", (_e, snap) => cb(snap)),
  onPinned: (cb) => ipcRenderer.on("usage://pinned", (_e, pinned) => cb(pinned)),
  refresh: () => ipcRenderer.send("usage://refresh"),
  hideOverlay: () => ipcRenderer.send("usage://overlay-hide"),
  setOverlayHit: (hit) => ipcRenderer.send("usage://overlay-hit", hit),
  hideFlyout: () => ipcRenderer.send("usage://flyout-hide"),
  togglePin: () => ipcRenderer.send("usage://overlay-toggle-pin"),
  toggleFlyout: () => ipcRenderer.send("usage://flyout-toggle"),
  openTrayMenu: () => ipcRenderer.send("usage://tray-menu"),
  openUsage: (id) => ipcRenderer.send("usage://open-usage", id),
  resizeOverlay: (h, w) => ipcRenderer.send("usage://overlay-resize", h, w),
  getInterval: () => ipcRenderer.invoke("usage://get-interval"),
  setIntervalSecs: (secs) => ipcRenderer.send("usage://set-interval", secs),
  onInterval: (cb) => ipcRenderer.on("usage://interval", (_e, secs) => cb(secs)),
  setChipsHit: (hit) => ipcRenderer.send("usage://chips-hit", hit),
  resizeChips: (w, h) => ipcRenderer.send("usage://chips-resize", w, h),
  getChipsDocked: () => ipcRenderer.invoke("usage://get-chips-docked"),
  onChipsDocked: (cb) => ipcRenderer.on("usage://chips-docked", (_e, docked) => cb(docked)),
  setFlyoutHit: (hit) => ipcRenderer.send("usage://flyout-hit", hit),
  resizeFlyout: (h, w) => ipcRenderer.send("usage://flyout-resize", h, w),
  toggleFlyoutPin: () => ipcRenderer.send("usage://flyout-toggle-pin"),
  toggleFlyoutDock: () => ipcRenderer.send("usage://flyout-toggle-dock"),
  getFlyoutState: () => ipcRenderer.invoke("usage://get-flyout-state"),
  onFlyoutState: (cb) => ipcRenderer.on("usage://flyout-state", (_e, state) => cb(state)),
  dragBegin: (sx, sy) => ipcRenderer.send("usage://drag-begin", sx, sy),
  dragTo: (sx, sy) => ipcRenderer.send("usage://drag-to", sx, sy),
  dragEnd: () => ipcRenderer.send("usage://drag-end"),
});
