const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("usage", {
  onSnapshot: (cb) => ipcRenderer.on("usage://snapshot", (_e, snap) => cb(snap)),
  onLoading: (cb) => ipcRenderer.on("usage://loading", () => cb()),
  refresh: () => ipcRenderer.send("usage://refresh"),
  hideFlyout: () => ipcRenderer.send("usage://flyout-hide"),
  toggleFlyout: () => ipcRenderer.send("usage://flyout-toggle"),
  openTrayMenu: () => ipcRenderer.send("usage://tray-menu"),
  openNetwork: () => ipcRenderer.send("usage://open-network"),
  onNet: (cb) => ipcRenderer.on("usage://net", (_e, summary) => cb(summary)),
  onSystem: (cb) => ipcRenderer.on("usage://system", (_e, summary) => cb(summary)),
  openUsage: (id) => ipcRenderer.send("usage://open-usage", id),
  getInterval: () => ipcRenderer.invoke("usage://get-interval"),
  setIntervalSecs: (secs) => ipcRenderer.send("usage://set-interval", secs),
  onInterval: (cb) => ipcRenderer.on("usage://interval", (_e, secs) => cb(secs)),
  setChipsHit: (hit) => ipcRenderer.send("usage://chips-hit", hit),
  resizeChips: (w, h) => ipcRenderer.send("usage://chips-resize", w, h),
  getChipsDocked: () => ipcRenderer.invoke("usage://get-chips-docked"),
  onChipsDocked: (cb) => ipcRenderer.on("usage://chips-docked", (_e, docked) => cb(docked)),
  onChipsPopped: (cb) => ipcRenderer.on("usage://chips-popped", (_e, popped) => cb(popped)),
  onChipsFill: (cb) => ipcRenderer.on("usage://chips-fill", (_e, height) => cb(height)),
  setFlyoutHit: (hit) => ipcRenderer.send("usage://flyout-hit", hit),
  resizeFlyout: (h, w) => ipcRenderer.send("usage://flyout-resize", h, w),
  toggleFlyoutPin: () => ipcRenderer.send("usage://flyout-toggle-pin"),
  toggleFlyoutDock: () => ipcRenderer.send("usage://flyout-toggle-dock"),
  getFlyoutState: () => ipcRenderer.invoke("usage://get-flyout-state"),
  onFlyoutState: (cb) => ipcRenderer.on("usage://flyout-state", (_e, state) => cb(state)),
  dragBegin: (sx, sy) => ipcRenderer.send("usage://drag-begin", sx, sy),
  dragTo: (sx, sy) => ipcRenderer.send("usage://drag-to", sx, sy),
  dragEnd: () => ipcRenderer.send("usage://drag-end"),
  onUpdate: (cb) => ipcRenderer.on("usage://update", (_e, state) => cb(state)),
  onPrefs: (cb) => ipcRenderer.on("usage://prefs", (_e, prefs) => cb(prefs)),
  getPrefs: () => ipcRenderer.invoke("usage://get-prefs"),
  openSettings: () => ipcRenderer.send("usage://open-settings"),
  pairPhone: () => ipcRenderer.invoke("usage://pair-phone"),
  cancelPair: () => ipcRenderer.invoke("usage://pair-cancel"),
  getPairing: () => ipcRenderer.invoke("usage://get-pairing"),
  onPairing: (cb) => ipcRenderer.on("usage://pairing", (_e, status) => cb(status)),
  getUpdate: () => ipcRenderer.invoke("usage://get-update"),
  updateAction: () => ipcRenderer.send("usage://update-action"),
});
